import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { Tajawal } from "next/font/google";
import "./globals.css";

const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  variable: "--font-tajawal",
  display: "swap",
});

const SITE_URL = "https://tawfikdz.online";
const SITE_NAME = "توفيق";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),

  title: {
    default: "توفيق | دروس واختبارات وفروض لجميع المراحل في الجزائر",
    template: `%s | ${SITE_NAME}`,
  },

  description:
    "موقع توفيق — المنصة التعليمية الجزائرية المجانية. دروس، فروض محلولة، اختبارات للتعليم الابتدائي والمتوسط والثانوي. مواضيع وحلول شهادة BEM والبكالوريا BAC من 1996 حتى اليوم. بدون تسجيل.",

  keywords: [
    "توفيق", "الجزائر", "تعليم جزائر", "دروس", "اختبارات", "فروض محلولة",
    "بكالوريا", "باكالوريا", "مواضيع بكالوريا", "حلول بكالوريا", "بكالوريا جزائر",
    "BAC algérie", "sujets bac", "BEM", "شهادة التعليم المتوسط", "مواضيع BEM", "حلول BEM",
    "تعليم ابتدائي", "تعليم متوسط", "تعليم ثانوي",
    "رياضيات", "فيزياء", "لغة عربية", "لغة فرنسية", "علوم طبيعية",
    "فروض مع الحلول", "اختبارات محلولة", "تحضير للامتحانات", "مراجعة بكالوريا", "eddirasa",
    "morafik", "tawfikdz",
  ],

  authors: [{ name: "Tawfik", url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,

  // ── Icons — Next.js picks up icon.png + apple-icon.png from src/app automatically ──
  // These declarations make them explicit and add the 32px favicon fallback.
  icons: {
    icon: [
      { url: "/favicon.ico",  sizes: "any" },
      { url: "/icon.png",     sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/apple-icon.png", sizes: "180x180", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // OG image is auto-generated by opengraph-image.tsx — no need to hardcode the path
  openGraph: {
    title: "توفيق | دروس واختبارات وفروض لجميع المراحل في الجزائر",
    description:
      "المنصة التعليمية الجزائرية المجانية — دروس، فروض محلولة، مواضيع وحلول BAC و BEM. بدون تسجيل.",
    url: SITE_URL,
    siteName: SITE_NAME,
    locale: "ar_DZ",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "توفيق | دروس واختبارات وفروض في الجزائر",
    description:
      "المنصة التعليمية الجزائرية المجانية — دروس، فروض محلولة، مواضيع وحلول BAC و BEM.",
    site: "@tawfikdz",
    creator: "@tawfikdz",
  },

  alternates: {
    canonical: SITE_URL,
  },

  // Helps Google associate your site icon
  other: {
    "msapplication-TileColor": "#7C3AED",
    "msapplication-TileImage": "/icon.png",
    "theme-color": "#7C3AED",
  },
};

// ─── JSON-LD ──────────────────────────────────────────────────────────────────

const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: SITE_NAME,
  url: SITE_URL,
  description: "منصة تعليمية جزائرية مجانية تقدم دروساً واختبارات وفروضاً لجميع المراحل الدراسية",
  inLanguage: "ar",
  potentialAction: {
    "@type": "SearchAction",
    target: { "@type": "EntryPoint", urlTemplate: `${SITE_URL}/search?q={search_term_string}` },
    "query-input": "required name=search_term_string",
  },
  publisher: {
    "@type": "Organization",
    name: SITE_NAME,
    url: SITE_URL,
    logo: {
      "@type": "ImageObject",
      url: `${SITE_URL}/icon.png`,
      width: 512,
      height: 512,
    },
  },
};

const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "EducationalOrganization",
  name: SITE_NAME,
  url: SITE_URL,
  logo: `${SITE_URL}/icon.png`,
  sameAs: [`${SITE_URL}`],
  description:
    "موقع توفيق — منصة تعليمية جزائرية مجانية تقدم دروساً واختبارات وفروضاً للتعليم الابتدائي والمتوسط والثانوي، بالإضافة إلى مواضيع وحلول شهادتي BEM والبكالوريا.",
  areaServed: { "@type": "Country", name: "Algeria" },
  audience: { "@type": "EducationalAudience", educationalRole: "student" },
  teaches: ["التعليم الابتدائي", "التعليم المتوسط", "التعليم الثانوي", "البكالوريا", "BEM"],
  hasOfferCatalog: {
    "@type": "OfferCatalog",
    name: "محتوى تعليمي مجاني",
    itemListElement: [
      { "@type": "Offer", itemOffered: { "@type": "Course", name: "دروس التعليم الابتدائي" } },
      { "@type": "Offer", itemOffered: { "@type": "Course", name: "دروس التعليم المتوسط" } },
      { "@type": "Offer", itemOffered: { "@type": "Course", name: "دروس التعليم الثانوي" } },
      { "@type": "Offer", itemOffered: { "@type": "Course", name: "مواضيع وحلول البكالوريا" } },
      { "@type": "Offer", itemOffered: { "@type": "Course", name: "مواضيع وحلول BEM" } },
    ],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar" dir="rtl" className={`${tajawal.variable} scroll-smooth`}>
      <head>
        <meta name="google-site-verification" content="2KliwNjr6lQGipGCkHBXYyhrp8vGLMAspStZ_Dh-Huo" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} />
      </head>
      <body className={`${tajawal.className} antialiased bg-[#F7F3EC]`}>
        <Analytics />
        {children}
      </body>
    </html>
  );
}